---
title: "lab3b"
author: "Bryan Alpay"
date: "2025-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```


``` {r}


song_popularity <- c(94, 86, 80, 93, 63, 83, 91, 76, 92, 91, 70, 82, 82, 83, 79, 93, 70, 88, 75, 74, 80, 90, 85, 81, 96, 89, 81, 95, 67, 75, 87, 76, 85, 94, 76, 77, 85, 87, 96, 83, 77, 71, 74, 79, 85, 98, 92, 59, 72, 74, 90, 92, 75, 81, 83, 85, 92, 90, 75, 88, 68, 83, 89, 76, 33, 97, 96, 90, 91, 67, 87, 92, 76, 92, 100, 85, 87, 73, 74, 95, 91, 96, 85, 74, 86, 85, 67, 90, 84, 89, 89, 83, 71, 95, 93, 87)


song_popularity[30:41] %>%
  sum()

sort(song_popularity, decreasing = TRUE)[63]

song_popularity[96] < song_popularity[8]

```
``` {r}
song_length <- c(202735, 162680, 168873, 179720, 221693, 185422, 184893, 202133, 210560, 193346, 173381, 174000, 187943, 176146, 175163, 161853, 187111, 193279, 238805, 152137, 165760, 168601, 189560, 204316, 231041, 212878, 278440, 213718, 206385, 174680, 136266, 257213, 258799, 215281, 136760, 173549, 224773, 200000, 195013, 96825, 213493, 202226, 203807, 186173, 214405, 157890, 153000, 179426, 254181, 197442, 185855, 225148, 198324, 188918, 164818, 256000, 270586, 161840, 145800, 160656, 224694, 174728, 173182, 212000, 178147, 205946, 153190, 231832, 225664, 185680, 172626, 160239, 193506, 263288, 175344, 227527, 200547, 143901, 214613, 133613, 194050, 185600, 214416, 207065, 167480, 141805, 216120, 186677, 161266, 226088, 207853, 206772, 195760, 216764)

sum(song_length >= 153000)



```


``` {r}
song_title <- c("To Be Loved By You", "High", "Easy On Me", "We Don't Talk About Bruno", "If I Was a Cowboy", "pushin P (feat. Young Thug)", "Pressure", "Me or Sum (feat. Future & Lil Baby)", "Save Your Tears (with Ariana Grande) (Remix)", "Better Days (NEIKED x Mae Muller x Polo G)", "Dos Oruguitas", "Meet Me At Our Spot", "Levitating", "Rumors (feat. Lil Durk)", "TO THE MOON", "Cold Heart - PNAU Remix", "MAMIII", "Bussin", "All Of You", "Peru", "I'm Tired - From 'Euphoria' An HBO Original Series", "I Wish", "Sacrifice", "Smokin Out The Window", "Still D.R.E.", "Oh My God", "Surface Pressure", "By Your Side", "Come Back As A Country Boy", "Fancy Like", "Do We Have A Problem?", "Iffy", "'Til You Can't", "Worst Day", "THATS WHAT I WANT", "I Love You So", "You Should Probably Leave", "Essence (feat. Justin Bieber & Tems)", "Beautiful Lies", "Woman", "I Hate YoungBoy", "Never Wanted To Be That Girl", "AHHH HA", "Home Sweet", "abcdefu", "STAY (with Justin Bieber)", "Bad Habits", "INDUSTRY BABY (feat. Jack Harlow)", "Freaky Deaky", "What Else Can I Do?", "The Motto", "I Hate U", "Super Gremlin", "Need to Know", "Usain Boo", "Scorpio", "Knife Talk (with 21 Savage ft. Project Pat)", "Hrs and Hrs", "Fingers Crossed", "One Mississippi", "The Joker And The Queen (feat. Taylor Swift)", "Never Say Never (with Lainey Wilson)", "Banking On Me", "Don't Play That", "The Family Madrigal", "Enemy (with JID) - from the series Arcane League of Legends", "Doin' This", "good 4 u", "Shivers", "Light Switch", "Heart On Fire", "Buy Dirt", "AA", "half of my hometown (feat. Kenny Chesney)", "Circles Around This Town", "23", "When I’m Gone (with Katy Perry)", "Sand In My Boots", "City of Gods", "love nwantiti (ah ah ah)", "Big Energy", "Good Morning Gorgeous", "Do It To It", "P power (feat. Drake)", "she's all i wanna be", "Flower Shops (feat. Morgan Wallen)", "Boyfriend", "Ghost")

song_title[nchar(song_title) > 10]


```


``` {r}
song_data <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vS8ynnfEAOH9G59D6ZS0EhW6X9taKBE2ou0Z6qO_XJUzwCuD_DjNvDNRNuouNivlgptmqyqBZYsrKTs/pub?gid=1225680565&single=true&output=csv")

song_data %>%
  arrange(desc(track_id)) %>%
  select(track_id, artist_name) %>%
  print()

```


```{r}
song_data %>%
  filter(rand_var < 0.39) %>%
  nrow()

```
```{r}
song_title <- c("Waiting On A Miracle", "P power (feat. Drake)", "City of Gods", "I Love You So", "Banking On Me", "The Joker And The Queen (feat. Taylor Swift)", "The Motto", "Circles Around This Town", "High", "If I Was a Cowboy", "I'm Tired - From 'Euphoria' An HBO Original Series", "I Hate YoungBoy", "Do It To It")

song_length <- c(161840, 193346, 256000, 160239, 200000, 185422, 164818, 195760, 175163, 195013, 187943, 261818, 157890)

song_popularity <- c(87, 85, 87, 95, 83, 89, 94, 76, 87, 77, 88, 70, 95)

song_data <- tibble(song_title, song_length, song_popularity)

mutated <- song_data %>%
  mutate(song_income  = (song_length * 0.04))%>%
  select(song_income, song_title)

slice(mutated, 12)


mutated <- song_data %>%
  mutate(song_title_lower = str_to_lower(song_title)) %>%
  select(song_title_lower, song_title ) %>%
  print()


mutated %>% 
  filter(str_detect(song_title_lower, 'c')) %>%
  nrow()

```


```{r}


```