---
title: "lab3b"
author: "Bryan Alpay"
date: "2025-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(jsonlite)
```

```{r}

query <- "https://stat.auckland.ac.nz/~fergusson/stats220_S124/data/lab3b_json34.json"

song_data <- fromJSON(query)

knitr::kable(song_data)


```



```{r}
song_data %>%
  slice(2)


```



```{r}
duration_pull <- song_data %>%
  pull(duration_ms)

length(duration_pull)

```



```{r}
song_data %>%
  pull(duration_ms)%>%
  median()
```

```{r}
song_data %>%
  pull(track_popularity)%>%
  unique()%>%
  length()
```

```{r}
seperated <- song_data %>%
  separate_rows(artist_name, sep=",")

#sort(seperated$artist_)

uniqueV <- seperated %>%
  pull(artist_name)%>%
  unique()

sort(uniqueV)

```
```{r}
song_data %>%
  filter(track_popularity > 80 & str_count(str_to_lower(artist_genre), "pop"))%>%
  nrow()
```
```{r}
pop_songs <- song_data %>%
  mutate(pop = ifelse(str_count(str_to_lower(artist_genre), "pop"), "yes", "no"))

pop_songs %>%
  slice(33) %>%
  print()

```

```{r}
pop_songs %>%
  group_by(pop) %>%
  summarise(median_popularity = median(track_popularity))


```

```{r}
long_songs<- song_data %>%
  mutate(track_name_num_words = str_count(track_name, "\\S+"))

long_songs %>%
  slice(7)%>%
  print()

```
```{r}

sum(long_songs$track_name_num_words > 5)

```

